#pragma once
#include <afxwin.h>
#include "resource.h"
#include <map>
#include <queue>
#include <thread>
#include <winsock2.h>
#include <afxdialogex.h>
#include <string>
using std::string;
using std::map;
using std::queue;